### ISSUE TITLE
how to sync Grambank and UraTyp

### ISSUE THREAD

**Issue by HedvigS** [bedlan/uratyp-1#10]
Should we 

a) sync the raw coding sheets before a release of UraTyp or Grambank 
b) sync a published release version of UraTyp/Grambank into the other before a release

?

**Comment by xrotwang** [comment]
Sync a published, released version of UraTyp into Grambank before releasing Grambank.

**Comment by HedvigS** [comment]
I had a different understanding from @xrotwang about what the three of us (me, @MiinaNo and @xrotwang ) said about this syncing over a year ago. I prefer (a). Robert prefers (b).

**Comment by MiinaNo** [comment]
Instead of supporting one or the other option I could say a few words about my plans. Since I have a small project until December, in the upcoming months, the plan is to check the languages we did not manage to check for the Grambank release (i.e., about 10 Uralic languages). Thus, at some point in October/November we could release UraTyp 2.0 (probably this would mean that  also option (b) could work for the next Grambank release). Or would it make sense to update also UraTyp with what we have right now? 

PS. In case you have any suggestions or comments (of the type try to avoid doing that or definitely do that) then you are most welcome to share. I will definitely make sure that comma separated file would not turn into something else.

**Comment by HedvigS** [comment]
> Instead of supporting one or the other option I could say a few words about my plans. Since I have a small project until December, in the upcoming months, the plan is to check the languages we did not manage to check for the Grambank release (i.e., about 10 Uralic languages). Thus, at some point in October/November we could release UraTyp 2.0 (probably this would mean that also option (b) could work for the next Grambank release). Or would it make sense to update also UraTyp with what we have right now?
> 

I don't know, for UraTyp release schedule I don't have any opinions  or suggestions. Grambank releases are tied up with specific papers  so we make fewer releases and there is more at play than just the data release itself. If UraTyp don't have such concerns, you could choose to release versions more often.

What is the plan for UraTyp updates and releases the next 4 years? Is it going to be significantly continuously updated, or is it likely to reach a saturation level of edits soon?

**Comment by MiinaNo** [comment]
1. Ok, I get it. Probably next UraTyp release could be associated with a paper but let's see.

2. I think that the likely scenario for the next 4 years is the latter, i.e. that it will "reach a saturation level of edits soon". With the 10+ remaining language the idea is to add examples and proper sources, which means somewhat bigger changes, but once we are done, hopefully it will not be significantly updated. Thus, UraTyp 2.0 could be a significantly updated version but after that only smaller changes are necessary, I guess.

**Comment by HedvigS** [comment]
Okay! 

I'm sorry if I misunderstood what we three talked about a while back, I really thought we had decided to sync the raw datasets before a release of either. I'm happy to do whatever is best for you next time round.

**Comment by xrotwang** [comment]
So that's a b) then.
